### ISSUE TITLE
the same bug in UIDevice+BFKit.h about SCREEN_WIDTH and SCREEN_HEIGHT

### ISSUE THREAD

**Issue by jiongge** [FabrizioBrancati/BFKit#13]
the same bug in UIDevice+BFKit.h about SCREEN_WIDTH and SCREEN_HEIGHT... BFKit-Swift has fixt it.Just a reminder :)

**Comment by FabrizioBrancati** [comment]
Yes I know, BFKit is behind BFKit-Swift.
I've planned to fix it here as soon as possible!
Thanks for the reminder ;)

**Comment by rdmehta09** [comment]
Why I am getting these notifications ? I never subscribed to this.

On Wed, Jul 15, 2015 at 4:30 PM, Fabrizio Brancati <notifications@github.com

**Comment by FabrizioBrancati** [comment]
Thanks! :+1:
