### ISSUE TITLE
Use of @import when modules are disabled

### ISSUE THREAD

**Issue by tobatha** [FabrizioBrancati/BFKit#14]
Hey dude,

when i add BFKit folder to my project and #import "BFKit.h"
the errors pop:
Use of "@import" when modules are disabled

and i checked my build settings, it's all good, and i added all the required frameworks, so it's very weird
![image](https://cloud.githubusercontent.com/assets/2382153/8867761/883bb6b2-3200-11e5-9473-15ecc7c8ae07.png)

**Comment by FabrizioBrancati** [comment]
Have you tried to create a new project and import BFKit?

**Comment by FabrizioBrancati** [comment]
This is a very general question that isn't specific to this library.
In the future please look it up before you open an issue.
