### ISSUE TITLE
bug in NSFileManager+BFKit.m

### ISSUE THREAD

**Issue by jiongge** [FabrizioBrancati/BFKit#15]
" [self moveLocalFile:[NSString stringWithFormat:@"%@-Settings.plist", settings] fromDirectory:DirectoryTypeMainBundle toDirectory:DirectoryTypeLibrary withFolderName:@""] " in  (id)getSettings:(NSString *)settings  objectForKey:(NSString *)objKey  and  (BOOL)setSettings:NSString *)settings  object:(id)value forKey:(NSString *)objKey;

if "withFolderName:@""" the %@-Settings.plist will be a folder with the name "/Library/App-Settings.plist/",isn't a file

 ([[NSFileManager defaultManager] copyItemAtPath:originPath toPath:destinationPath error:nil]) will  fail because there has had a  file  "  %@-Settings.plist ",but it's a folder,can not be read as a pist

the same bug in swift version

**Comment by FabrizioBrancati** [comment]
I'll investigate on it.

Thanks :smile:

**Comment by jiongge** [comment]
another bug in this function

+ (BOOL)setSettings:(NSString *)settings object:(id)value forKey:(NSString *)objKey
{
    NSString *path = [self getLibraryDirectoryForFile:[NSString stringWithFormat:@"%@-Settings.plist", settings]];
    NSMutableDictionary *loadedPlist = [NSMutableDictionary dictionaryWithContentsOfFile:path];
    
    if(![[NSFileManager defaultManager] fileExistsAtPath:path])
    {
        //path = [[NSBundle mainBundle] pathForResource:[NSString stringWithFormat:@"%@-Settings", settings] ofType:@"plist"];
        [self moveLocalFile:[NSString stringWithFormat:@"%@-Settings.plist", settings] fromDirectory:DirectoryTypeMainBundle toDirectory:DirectoryTypeLibrary withFolderName:nil];
        loadedPlist = [NSMutableDictionary dictionaryWithContentsOfFile:path];
    }
    
    [loadedPlist setObject:value forKey:objKey];
    
    return [loadedPlist writeToFile:path atomically:YES];
}

the "path = [[NSBundle mainBundle] pathForResource:[NSString stringWithFormat:@"%@-Settings", settings] ofType:@"plist"];" i think it  is redundant and the result is wrong with it

**Comment by FabrizioBrancati** [comment]
Tomorrow I'll fix that! :wink:

**Comment by FabrizioBrancati** [comment]
Thanks! :smile:
