### ISSUE TITLE
NSString+BFKit  maybe crash 

### ISSUE THREAD

**Issue by BoBoMoon** [FabrizioBrancati/BFKit#18]
+ (NSString *)searchInString:(NSString *)string charStart:(char)start charEnd:(char)end

This method,if I enter two identical characters,it will crash;

For example:
NSString *search = @"Search in #this# string!";
BFLog(@"Search: %@", [search searchCharStart:'#' charEnd:'#'])
it will crash.
I did a little bit of repair.

+ (NSString *)searchInString:(NSString *)string charStart:(char)start charEnd:(char)end
{
    int inizio = 0, stop = 0;
    
    for(int i = 0; i < [string length]; i++)
    {
        if([string characterAtIndex:i] == start && inizio == 0)
        {
            inizio = i+1;
            i += 1;
            continue;
        }
        if([string characterAtIndex:i] == end)
        {
            stop = i;
            break;
        }
    }
    
    stop -= inizio;
    
    return [[string substringFromIndex:inizio] substringToIndex:stop];
}

**Comment by FabrizioBrancati** [comment]
Your code fixed the crash?

**Comment by BoBoMoon** [comment]
Yes, it is.

**Comment by FabrizioBrancati** [comment]
I added this line before return to avoid crashes:
`if (end < 0) end = 0;`

**Comment by FabrizioBrancati** [comment]
Thanks! :+1:
