### ISSUE TITLE
imageAtRect:(CGRect)rect not working properly for iPhone 6S Plus

### ISSUE THREAD

**Issue by mihir815** [FabrizioBrancati/BFKit#26]
File : BFKit/Source/Additions/UIKit/UIImage+BFKit.m
Method : - (UIImage * _Nonnull)imageAtRect:(CGRect)rect

Not working with the image scale > 2 but working image scale <=2

**Comment by FabrizioBrancati** [comment]
Can you provide me some info on how to reproduce it?
Thanks

**Comment by mihir815** [comment]
Capture one image on iPhone 6s Plus and equally divide in 3 horizontal box with some indicator border.
After then get the frame of each box and try - (UIImage * _Nonnull)imageAtRect:(CGRect)rect method to get the image of each box rectangle.

It will crop the zoomed area of image.

**Comment by FabrizioBrancati** [comment]
Sorry for late reply and thanks! 👍
