### ISSUE TITLE
Support Language Issues

### ISSUE THREAD

**Issue by Connerli** [FabrizioBrancati/BFKit#34]
When I used BFKit, my app support language on appstory changed to 10 types. I think it's the BFKit language file. Do you have any good Suggestions to solve this problem? I'm not sure it's a BFKit problem. Thank you very much!
![image](https://user-images.githubusercontent.com/16755393/34665762-6ab6920e-f49c-11e7-903e-827a82cbfce0.png)

**Comment by Connerli** [comment]
I just want the APP to support simplified Chinese.

**Comment by FabrizioBrancati** [comment]
How did you add BFKit to your App?
By copy-paste the files?

**Comment by Connerli** [comment]
@FabrizioBrancati NO,by Cocoapods.

**Comment by FabrizioBrancati** [comment]
Maybe you just need to remove the unwanted languages from your App project, but I'll investigate more

**Comment by Connerli** [comment]
OK,I don't have a better way.Thank you！
