### ISSUE TITLE
Logic error of UIView's extension function: cornerRadius(corners: UIRectCorner, radius: CGFloat)

### ISSUE THREAD

**Issue by kokitang** [FabrizioBrancati/BFKit#35]

**Comment by kokitang** [comment]
```
if corners.contains(.bottomLeft) {
                    cornerMask.update(with: .layerMinXMinYCorner)
                }
                if corners.contains(.bottomRight) {
                    cornerMask.update(with: .layerMaxXMinYCorner)
                }
                if corners.contains(.topLeft) {
                    cornerMask.update(with: .layerMinXMaxYCorner)
                }
                if corners.contains(.topRight) {
                    cornerMask.update(with: .layerMaxXMaxYCorner)
                }
```
Should be:

```
if corners.contains(.bottomLeft) {
                    cornerMask.update(with: .layerMinXMaxYCorner)
                }
                if corners.contains(.bottomRight) {
                    cornerMask.update(with: .layerMaxXMaxYCorner)
                }
                if corners.contains(.topLeft) {
                    cornerMask.update(with: .layerMinXMinYCorner)
                }
                if corners.contains(.topRight) {
                    cornerMask.update(with: .layerMaxXMinYCorner)
                }
```

**Comment by kokitang** [comment]
in iOS 10:
<img width="327" alt="2018-07-10 2 13 59" src="https://user-images.githubusercontent.com/17448093/42492417-992f4b1e-844b-11e8-96cb-41e8afc2fa63.png">

in iOS 11:
<img width="322" alt="2018-07-10 2 14 18" src="https://user-images.githubusercontent.com/17448093/42492431-a2fd67de-844b-11e8-8ca4-5dff451b9ffb.png">

Code:
cornerRadius(corners: [.topLeft, .topRight, .bottomRight], radius: 16)

**Comment by FabrizioBrancati** [comment]
Thanks! Why not open a pull request? 😄 
Just a question, they changed the Y asix on iOS 11?

**Comment by kokitang** [comment]
Haha.. My source control software having some issue on push code to GitHub..

I don't think they changed the Y axis stuffs on iOS 11 due to coordinate x: 0, y: 0 is top-left corner. And in your original code you state .bottomLeft is minimum X and minimum Y, so it's not correct obviously.

**Comment by FabrizioBrancati** [comment]
Ahah ok I will fix it.
I don't understand your previous comment, both the images are generated by the same code `cornerRadius(corners: [.topLeft, .topRight, .bottomRight], radius: 16)`?
Or is a "How is now" and "How has to be"?

**Comment by FabrizioBrancati** [comment]
@kokitang News about that issue?
