### ISSUE TITLE
Error "Type of expression is ambiguous" between Timer and NSObject extension

### ISSUE THREAD

**Issue by tony-hoang999** [FabrizioBrancati/BFKit#39]
Hello,

I'm getting a compiler error "Type of expression is ambiguous without more context". 
Basically, it's the conflict between ```NSObject.isValid()``` and ```Timer.isValid```. 

I've noticed that 'isValid' is quite commonly used in some other third party libraries, e.g: Firebase. I wonder if it should be renamed to something else to avoid this conflict.

Cheers.

**Comment by FabrizioBrancati** [comment]
Hi @tony-hoang999 I renamed the function from `isValid` to `isObjectValid` to avoid conflicts with other libraries 😉 
You can find it on version [2.0.0](https://github.com/FabrizioBrancati/BFKit/releases/tag/v2.0.0) (major bumping was required by this and other breaking changes).

**Comment by tony-hoang999** [comment]
Thanks @FabrizioBrancati 👍
