### ISSUE TITLE
UIWebView deprecated issue in ObjectiveC Pod file

### ISSUE THREAD

**Issue by Jagathesh-IOS** [FabrizioBrancati/BFKit#41]
Actually, i'm using this pod file for my ObjectiveC projects. and, it's contains UIWebView classes.
As per the apple guidelines this is deprecated & you guys are fixed this issue on Swift pod file.

pod 'BFKit'
Could you please update this for ObjectiveC Pod file?

**Comment by FabrizioBrancati** [comment]
Done! You can use the new [3.0.0](https://github.com/FabrizioBrancati/BFKit/releases/tag/v3.0.0) version 😉

**Comment by Jagathesh-IOS** [comment]
Thanks 😘
