### ISSUE TITLE
Fuc 'reversedArray' return wrong

### ISSUE THREAD

**Issue by iunion** [FabrizioBrancati/BFKit#8]
+ (NSArray *)reversedArray:(NSArray*)array
{
    NSMutableArray *arrayTemp = [NSMutableArray arrayWithCapacity:[array count]];
    NSEnumerator *enumerator = [array reverseObjectEnumerator];
    
    for(id element in enumerator) [arrayTemp addObject:element];
    
    return array;
}

correct:
return arrayTemp;

**Comment by FabrizioBrancati** [comment]
Thanks! :)
